worker_processes 1;

events {
    worker_connections 1024;
}

http {
    lua_shared_dict risk_scores 10m;
    lua_shared_dict ip_sessions 10m;

    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    upstream real_system {
        server 10.0.0.2:8080;
    }

    upstream honeypot {
        server 10.0.0.3:8001;
    }

    server {
        listen 80;

        location / {
            set $risk_score 0;
            access_by_lua_file /etc/nginx/lua/risk_engine.lua;
            proxy_pass http://real_system;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_hide_header X-Powered-By;
            proxy_hide_header Server;
            add_header Server nginx always;
            proxy_pass_header Set-Cookie;
        }

        location @real_system {
            internal;
            proxy_pass http://real_system;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_hide_header X-Powered-By;
            proxy_hide_header Server;
            add_header Server nginx always;
            proxy_pass_header Set-Cookie;
            proxy_connect_timeout 10s;
            proxy_read_timeout    120s;
            proxy_send_timeout    120s;
        }

        location @honeypot {
            internal;
            proxy_pass http://honeypot;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Risk-Score $risk_score;
            proxy_hide_header X-Powered-By;
            proxy_hide_header Server;
            add_header Server nginx always;
            proxy_pass_header Set-Cookie;
            proxy_connect_timeout 10s;
            proxy_read_timeout    120s;
            proxy_send_timeout    120s;
        }
    }
}
